### ISSUE TITLE
fix undefined reference to `SystemInit'

### ISSUE THREAD

**Issue by HannesGitH** [HannesGitH/SWP_Telematik#28]
This Error arose out of nowhere: ```C:/Users/hanne/Documents/UNI/Sem1/swp/SWP/SWP_Telematik/Demonstrator/STM32CubeIDE/Secure/Debug/../Application/Startup/startup_stm32l552zetxq.s:94: undefined reference to `SystemInit'```

Neither any prior version nor a freshly cleaned project solved this..

**Comment by HannesGitH** [comment]
The whole Error:
```arm-none-eabi-gcc -o "Demonstartor_NonSecure.elf" @"objects.list" C:/Users/hanne/Documents/UNI/Sem1/swp/SWP/SWP_Telematik/Demonstrator/STM32CubeIDE/Secure/Debug/secure_nsclib.o  -mcpu=cortex-m33 -T"C:\Users\hanne\Documents\UNI\Sem1\swp\SWP\SWP_Telematik\Demonstrator\STM32CubeIDE\NonSecure\STM32L552ZETXQ_FLASH.ld" --specs=nosys.specs -Wl,-Map="Demonstartor_NonSecure.map" -Wl,--gc-sections -static --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wl,--start-group -lc -lm -Wl,--end-group
Application/Startup/startup_stm32l552zetxq.o: In function `LoopFillZerobss':
C:/Users/hanne/Documents/UNI/Sem1/swp/SWP/SWP_Telematik/Demonstrator/STM32CubeIDE/NonSecure/Debug/../Application/Startup/startup_stm32l552zetxq.s:94: undefined reference to `SystemInit'
Application/User/main.o: In function `main':
C:/Users/hanne/Documents/UNI/Sem1/swp/SWP/SWP_Telematik/Demonstrator/NonSecure/Src/main.c:90: undefined reference to `HAL_Init'
C:/Users/hanne/Documents/UNI/Sem1/swp/SWP/SWP_Telematik/Demonstrator/NonSecure/Src/main.c:111: undefined reference to `BSP_LED_Init'
C:/Users/hanne/Documents/UNI/Sem1/swp/SWP/SWP_Telematik/Demonstrator/NonSecure/Src/main.c:115: undefined reference to `osKernelInitialize'
C:/Users/hanne/Documents/UNI/Sem1/swp/SWP/SWP_Telematik/Demonstrator/NonSecure/Src/main.c:135: undefined reference to `osThreadNew'
C:/Users/hanne/Documents/UNI/Sem1/swp/SWP/SWP_Telematik/Demonstrator/NonSecure/Src/main.c:138: undefined reference to `osThreadNew'
C:/Users/hanne/Documents/UNI/Sem1/swp/SWP/SWP_Telematik/Demonstrator/NonSecure/Src/main.c:149: undefined reference to `osKernelStart'
Application/User/main.o: In function `SystemClock_Config':
C:/Users/hanne/Documents/UNI/Sem1/swp/SWP/SWP_Telematik/Demonstrator/NonSecure/Src/main.c:174: undefined reference to `HAL_PWREx_ControlVoltageScaling'
C:/Users/hanne/Documents/UNI/Sem1/swp/SWP/SWP_Telematik/Demonstrator/NonSecure/Src/main.c:192: undefined reference to `HAL_RCC_OscConfig'
C:/Users/hanne/Documents/UNI/Sem1/swp/SWP/SWP_Telematik/Demonstrator/NonSecure/Src/main.c:205: undefined reference to `HAL_RCC_ClockConfig'
Application/User/main.o: In function `LED_Thread':
C:/Users/hanne/Documents/UNI/Sem1/swp/SWP/SWP_Telematik/Demonstrator/NonSecure/Src/main.c:254: undefined reference to `vPortAllocateSecureContext'
C:/Users/hanne/Documents/UNI/Sem1/swp/SWP/SWP_Telematik/Demonstrator/NonSecure/Src/main.c:260: undefined reference to `osDelay'
Application/User/main.o: In function `LEDStripper':
C:/Users/hanne/Documents/UNI/Sem1/swp/SWP/SWP_Telematik/Demonstrator/NonSecure/Src/main.c:276: undefined reference to `LEDController__initialize'
C:/Users/hanne/Documents/UNI/Sem1/swp/SWP/SWP_Telematik/Demonstrator/NonSecure/Src/main.c:279: undefined reference to `osDelay'
C:/Users/hanne/Documents/UNI/Sem1/swp/SWP/SWP_Telematik/Demonstrator/NonSecure/Src/main.c:280: undefined reference to `LEDController__setRGB'
C:/Users/hanne/Documents/UNI/Sem1/swp/SWP/SWP_Telematik/Demonstrator/NonSecure/Src/main.c:281: undefined reference to `osDelay'
C:/Users/hanne/Documents/UNI/Sem1/swp/SWP/SWP_Telematik/Demonstrator/NonSecure/Src/main.c:282: undefined reference to `LEDController__setRGB'
Application/User/main.o: In function `Error_Handler':
C:/Users/hanne/Documents/UNI/Sem1/swp/SWP/SWP_Telematik/Demonstrator/NonSecure/Src/main.c:316: undefined reference to `BSP_LED_On'
Application/User/stm32l5xx_it.o: In function `TIM6_IRQHandler':
C:/Users/hanne/Documents/UNI/Sem1/swp/SWP/SWP_Telematik/Demonstrator/NonSecure/Src/stm32l5xx_it.c:112: undefined reference to `HAL_TIM_IRQHandler'
collect2.exe: error: ld returned 1 exit status
make: *** [makefile:57: Demonstartor_NonSecure.elf] Error 1
"make -j4 all" terminated with exit code 2. Build might be incomplete.
```

**Comment by HannesGitH** [comment]
workspace reset did it for old versions,

bug seems to be introduced in d98ba55c7fe81dd39aca5ca01f7ae88071a8fb48

**Comment by HannesGitH** [comment]
> bug seems to be introduced in [d98ba55](https://github.com/HannesGitH/SWP_Telematik/commit/d98ba55c7fe81dd39aca5ca01f7ae88071a8fb48)

Dieser und der vorherige commit sollten auch überhaupt nicht im dev sein
